blueprint:
  name: Boiler Toggle with Timer
  description: >
    This blueprint toggles a boiler and timer using an input_boolean.
    - When input_boolean is turned ON: boiler turns ON and timer starts.
    - When input_boolean is turned OFF: boiler turns OFF and timer is canceled.
  domain: automation
  input:
    boiler_switch:
      name: Boiler Switch
      description: The switch that turns the boiler on/off.
      selector:
        entity:
          domain: switch
    timer_entity:
      name: Boiler Timer
      description: The timer entity used for countdown.
      selector:
        entity:
          domain: timer
    trigger_entity:
      name: Trigger Button
      description: The input_boolean used to toggle the boiler.
      selector:
        entity:
          domain: input_boolean
    duration:
      name: Run Duration (minutes)
      description: Duration in minutes the boiler should run.
      default: 60
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes

trigger:
  - platform: state
    entity_id: !input trigger_entity

action:
  - variables:
      run_minutes: !input duration
      trigger_state: "{{ trigger.to_state.state }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger_state == 'on' }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input boiler_switch
          - service: timer.start
            target:
              entity_id: !input timer_entity
            data:
              duration: >
                00:{{ '%02d' | format(run_minutes | int) }}:00

      - conditions:
          - condition: template
            value_template: "{{ trigger_state == 'off' }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input boiler_switch
          - service: timer.cancel
            target:
              entity_id: !input timer_entity

mode: restart
